name: Sync GitHub Pages

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
          persist-credentials: false

      - name: Push to torch-diffsim.github.io
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote add pages https://x-access-token:${{ secrets.GH_PAT }}@github.com/torch-diffsim/torch-diffsim.github.io.git
          git push pages gh-pages:main --force

